### ISSUE TITLE
app.model: namespace should be defined

### ISSUE THREAD

**Issue by Jam1zhu** [sunny920406/roadhogWebpack4#10]
`npm run start:local`运行起来了
但是有错误
```
Uncaught Invariant Violation: app.model: namespace should be defined
````
不知道什么原因，求大神指教。

**Comment by sunny920406** [comment]
@Jam1zhu 这个错误应该是自身业务代码里的错

**Comment by Jam1zhu** [comment]
@sunny920406 已经解决了，异步加载改成require('xxx').default就行了。谢谢

**Comment by sunny920406** [comment]
@Jam1zhu 是的，我忘记在文档里说webpack4里异步加载是要改成require('xxx').default的,以前版本是不用加.default的
